### ISSUE TITLE
Build process doesn't start

### ISSUE THREAD

**Issue by ezbinden** [dhlab-basel/docker-sipi#1]
I'm trying to build sipi from docker-sipi.

The build process does not seem to work:

   ez$ docker build -t dhlabbasel/sipi
   "docker build" requires exactly 1 argument.
   See 'docker build --help'.

   Usage:  docker build [OPTIONS] PATH | URL | -

   Build an image from a Dockerfile

What's wrong?

**Comment by subotic** [comment]
you are missing the `.` at the end:

```
$ docker build -t dhlabbasel/sipi .
```

If you need Docker images of Sipi, then you can get them [here](https://hub.docker.com/r/dhlabbasel/sipi).

If you are not changing the Sipi source code, I wouldn't bother with building from source. It takes to long.

**Comment by ezbinden** [comment]
Ok
The . also missing in the readme file...

I realized, Sipi is already running in the Knora context on my box.  Can Salsah1 use it or does this confilct with Knora?

**Comment by subotic** [comment]
Thanks, I've updated the Readme.
